# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.IntegerField(primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=100)),
            ],
        ),
    ]
