# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='primary_subject',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='program',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='secondary_subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyareas.Program'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyareas.Program'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, through='students.SpecEnrolled', to='studyareas.Specialization'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyareas.Program'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, through='students.SpecGrad', to='studyareas.Specialization'),
        ),
        migrations.AlterField(
            model_name='specenrolled',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyareas.Specialization'),
        ),
        migrations.AlterField(
            model_name='specgrad',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyareas.Specialization'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
