# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 20:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=6)),
                ('program', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(11111111), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AddField(
            model_name='enroll',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set([('student_number', 'session')]),
        ),
    ]
