# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170523_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='session',
            field=models.ForeignKey(default='2016W', on_delete=django.db.models.deletion.CASCADE, to='students.Session'),
            preserve_default=False,
        ),
    ]
