# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_graduation_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='grad_application_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetables.GradAppStatus'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='status_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetables.GradAppReason'),
        ),
    ]
