# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_auto_20170504_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('session', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1111), django.core.validators.MaxValueValidator(3000)])),
                ('code', models.CharField(max_length=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('year', 'code')]),
        ),
    ]
