# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170504_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Session'),
        ),
    ]
