# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170523_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='award',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='students.Student'),
        ),
    ]
