# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170601_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(11111111), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
