# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170601_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='ceremony_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
