# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170601_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applied',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='most_recent_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Enroll'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_award_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
