# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20170510_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri_sec', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='primary_specialization',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='code',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialization',
            name='subject',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='specenrolled',
            name='enroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Enroll'),
        ),
        migrations.AddField(
            model_name='specenrolled',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Specialization'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, through='students.SpecEnrolled', to='students.Specialization'),
        ),
    ]
