# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 22:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0002_auto_20170525_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_auto_20170601_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('transfer_credits', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sub_type',
            new_name='self_id',
        ),
        migrations.AddField(
            model_name='graduation',
            name='conferral_period_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='conferral_period_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='financial_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='conferral_period',
            field=models.DateField(default=datetime.datetime(2017, 6, 5, 22, 0, 45, 331386, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduation',
            name='program',
            field=models.ForeignKey(default='MSC', on_delete=django.db.models.deletion.CASCADE, to='studyareas.Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specenrolled',
            name='enroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specenroll', to='students.Enroll'),
        ),
        migrations.AlterField(
            model_name='specenrolled',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specenroll', to='studyareas.Specialization'),
        ),
        migrations.AlterField(
            model_name='specgrad',
            name='graduation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specgrad', to='students.Graduation'),
        ),
        migrations.AlterField(
            model_name='specgrad',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specgrad', to='studyareas.Specialization'),
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='program_version',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='transfer_credits',
        ),
        migrations.AlterUniqueTogether(
            name='graduation',
            unique_together=set([('student_number', 'conferral_period', 'program')]),
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='session',
        ),
        migrations.AddField(
            model_name='previousinstitution',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_institutions', to='students.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='previousinstitution',
            unique_together=set([('student_number', 'institution_name')]),
        ),
    ]
