# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0002_auto_20170525_2003'),
        ('students', '0011_auto_20170606_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='specialization_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_g', to='studyareas.Specialization'),
        ),
        migrations.AddField(
            model_name='graduation',
            name='specialization_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_g', to='studyareas.Specialization'),
        ),
    ]
