# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170510_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specenrolled',
            unique_together=set([('specialization', 'enroll', 'pri_sec')]),
        ),
    ]
