# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20170511_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specenrolled',
            name='pri_sec',
            field=models.CharField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='specenrolled',
            unique_together=set([('enroll', 'pri_sec')]),
        ),
    ]
