# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170511_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
