# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20170725_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='status_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
