# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20170731_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='doctoral_citation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set([('student_number', 'session', 'award_title')]),
        ),
    ]
