# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20170817_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('session',)},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('session',)},
        ),
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ('session',)},
        ),
        migrations.AlterModelOptions(
            name='graduation',
            options={'ordering': ('conferral_period',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='self_id',
            field=models.CharField(blank=True, choices=[('NATI', 'First Nations'), ('INUI', 'Inuit'), ('METI', 'Métis'), ('STIN', 'Status Indian'), ('NSIN', 'Non-status Indian')], max_length=4, null=True),
        ),
    ]
