# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20170818_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='most_recent_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Enroll'),
        ),
    ]
