version: '2'
services:
  livedb:
    image: postgres
    volumes:
      - livedata:/var/lib/postgresql/data
  liveweb:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=dataproj.settings_prod
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - livedb

volumes:
  livedata:
    driver: local