# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialization',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
