# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0004_auto_20170615_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='is_health',
            field=models.BooleanField(default=False),
        ),
    ]
