# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0006_auto_20170623_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, choices=[('U', 'Undergraduate'), ('G', 'Graduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(blank=True, choices=[('Degree', 'Degree'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
