# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyareas', '0007_auto_20170818_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
