# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0005_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
