# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0006_tutorial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./files/', verbose_name='File'),
        ),
    ]
